// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2WyNkAPOj7ukAQIHSbTIUS-1UTlQNpAs',
    appId: '1:213395130394:web:5392e8d52417e3e338e9a3',
    messagingSenderId: '213395130394',
    projectId: 'come2werkauth-1bedc',
    authDomain: 'come2werkauth-1bedc.firebaseapp.com',
    storageBucket: 'come2werkauth-1bedc.appspot.com',
    measurementId: 'G-QYBP64LNSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOgw6D4nq7AE3ZmAVu8TkjJ8AgvgHdDsM',
    appId: '1:213395130394:android:dc17b57a6fc3063938e9a3',
    messagingSenderId: '213395130394',
    projectId: 'come2werkauth-1bedc',
    storageBucket: 'come2werkauth-1bedc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfKmFGcglpM9e5CJJ-ocUGaAslikOK5ug',
    appId: '1:213395130394:ios:d4093290e1531ffb38e9a3',
    messagingSenderId: '213395130394',
    projectId: 'come2werkauth-1bedc',
    storageBucket: 'come2werkauth-1bedc.appspot.com',
    iosBundleId: 'com.example.come2werkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfKmFGcglpM9e5CJJ-ocUGaAslikOK5ug',
    appId: '1:213395130394:ios:92a6733c4126ad1b38e9a3',
    messagingSenderId: '213395130394',
    projectId: 'come2werkauth-1bedc',
    storageBucket: 'come2werkauth-1bedc.appspot.com',
    iosBundleId: 'com.example.come2werkFlutter.RunnerTests',
  );
}
